"""
Sprint 3 canonical enrichment — BATCH 2: the final 13 instructional objects.
Same methodology as enrich_sprint3_canonical.py:
- 5 canonical fields VERBATIM from the Writing Elements Chart.
- Deeper Compass fields derived CONSERVATIVELY from the chart + the 4-pilot pattern.
- Per-field field_provenance. Pilots, related_elements (network), engine, prompts, architecture untouched.
"""
import json, os, copy

HERE = os.path.dirname(__file__)
KB_PATH = os.path.join(HERE, "..", "instructional_objects.json")
PILOTS = {"Thesis", "Evidence", "Explanation / Analysis", "Introduction"}
ENRICH_VERSION = "sprint3-canonical-v1"

ENGINE_USAGE = {
    "reader_function/writer_function": "target selection + interpretation (why this element matters now)",
    "performance_structure": "interpretation (gap between the attempt and the canonical function)",
    "functional_relationships": "target selection (is this the bottleneck vs a neighbor) + sequencing",
    "common_difficulties/recognition_diagnostics_detailed": "diagnostics (name what the learner is attempting + the likely misconception)",
    "productive_misconceptions": "instructional invitation (turn an error into a stepping stone, not a correction)",
    "indicators_of_development": "interpretation (degree_of_student_control) + stopping",
    "developmental_invitations": "instructional invitation (choose the invitation type; honor use_when/avoid_when; still ONE per turn)",
    "followup_decisions": "instructional decision (continue / redirect / increase or decrease support / change target / conclude)",
    "revision_strategies": "instructional invitation for revision (functional, not editing)",
    "stopping_conditions": "stopping / session closure",
    "transfer": "session closure (consolidation + a transfer note)",
}

def followups(component, neighbor):
    return [
        {"after": f"Learner improves the {component} in the targeted way.",
         "consider": "continue — consolidate the gain, then check the next-most-limiting aspect."},
        {"after": "Learner repeats the same difficulty after one invitation.",
         "consider": "increase_support — vary the scaffold (change the lens); do NOT supply the content."},
        {"after": f"The {component} now works but a neighbor is the real obstacle.",
         "consider": f"change_target to {neighbor} — this element is no longer the bottleneck."},
        {"after": "Learner independently performs and can explain the change.",
         "consider": "conclude this target — consolidate and release."},
        {"after": "Learner asks to proceed on their own.",
         "consider": "stop — hand back control (independence request)."},
    ]

def stopping(component):
    return [
        f"Learner independently produces a {component} that performs its canonical function for this reader and purpose.",
        "Diminishing returns — the element substantially works and further tuning yields little developmental gain.",
        "Another component has become the primary obstacle to communicating the meaning.",
        "Learner requests independence.",
        "Teacher override designates a different focus.",
    ]

CANON = {
 "Definition": [
  "An explanation of what a word, idea, or concept means in the present context.",
  "State the concept\u2019s basic meaning; identify its defining qualities; explain unfamiliar words within the explanation; distinguish it from related concepts when useful; elaborate until the intended reader can understand it.",
  "Is an important concept unexplained? Would the intended reader understand the explanation? Is it circular, vague, overly broad, overly narrow, or merely an example?",
  "Ask the student to explain the concept in ordinary language. Identify one unclear word or idea in that explanation and invite further elaboration.",
  "The student recognizes when a concept requires explanation and constructs appropriately complete definitions for different audiences and purposes.",
 ],
 "Concept": [
  "A general idea used to organize and interpret particular examples, experiences, or events.",
  "Name the idea; identify the qualities that make something an instance of it; distinguish central from incidental features; connect examples to the general idea; clarify its boundaries.",
  "Is the student using a term without understanding it? Are examples confused with the concept? Are defining qualities missing or inconsistent?",
  "Ask what different examples have in common and what would not count as an example. Help the student state the general idea.",
  "The student explains concepts abstractly, identifies valid and invalid examples, and uses concepts consistently in new contexts.",
 ],
 "Central Claim": [
  "A main assertion the writer asks the reader to understand, consider, or accept.",
  "State a clear position; define its scope; qualify it when necessary; make it supportable through reasons and evidence.",
  "Is there a genuine assertion? Is it clear and supportable? Is it too obvious, absolute, broad, or disconnected from the task?",
  "Ask what the writer wants the reader to believe and why someone might question it. Refine the assertion accordingly.",
  "The student produces precise, appropriately qualified claims and anticipates the support they require.",
 ],
 "Supporting Claim": [
  "A smaller assertion that helps establish or explain the essay\u2019s central claim.",
  "Identify one part of the central claim; state a relevant assertion about it; connect that assertion to the thesis; support it with reasoning or evidence.",
  "Does the paragraph make a claim rather than simply present information? Does the claim contribute to the thesis? Is its relationship to the thesis explicit?",
  "Ask, \u201cWhat does this paragraph help show about your thesis?\u201d Help the student formulate that contribution as a claim.",
  "Supporting claims become distinct, logically ordered, adequately supported, and clearly connected to the thesis.",
 ],
 "Example": [
  "A particular case used to clarify, illustrate, test, or support a general idea.",
  "Identify the idea needing illustration; choose a representative case; provide enough detail to make it understandable and to explain how example illustrates the idea.",
  "Is the idea too abstract for the reader? Is the example relevant and representative? Has the student explained what it demonstrates?",
  "Ask the student to provide a concrete case and identify exactly which features of the case illustrate the larger idea.",
  "The student chooses purposeful examples, explains their relevance, and recognizes when one example is insufficient or unrepresentative.",
 ],
 "Counterargument": [
  "A plausible alternative claim, objection, interpretation, or concern that challenges the writer\u2019s position.",
  "Identify a genuine point of disagreement; represent it accurately and fairly; explain the reasoning behind it; show why it matters to the argument.",
  "Is there a meaningful alternative perspective? Has it been ignored, caricatured, or reduced to an easily defeated objection?",
  "Ask what a thoughtful person might question or see differently. Help the student articulate the strongest reasonable version of that view.",
  "The student anticipates substantive objections, represents them charitably, and uses them to deepen rather than merely defend the argument.",
 ],
 "Rebuttal / Response": [
  "The writer\u2019s reasoned answer to a counterargument or objection.",
  "Acknowledge the counterargument; identify what is valid within it; explain its limits, errors, or different assumptions; revise or defend the original claim as needed.",
  "Does the response address the actual objection? Does it dismiss rather than engage? Should the original claim be qualified instead of simply defended?",
  "Ask what the counterargument gets right and where its reasoning no longer applies. Invite the student to refine the original position.",
  "The student responds directly, incorporates valid criticism, and strengthens or qualifies claims through engagement with alternatives.",
 ],
 "Qualification": [
  "Language that limits or specifies a claim so that it says no more and no less than the evidence supports.",
  "Identify the claim\u2019s boundaries; consider exceptions and uncertainty; specify conditions, groups, degree, probability, or timeframe; choose language that reflects those limits.",
  "Is the claim absolute, sweeping, or more certain than the evidence permits? Is it so qualified that it says almost nothing?",
  "Ask, \u201cIs this always true? For whom, under what conditions, and to what degree?\u201d Help the student revise the claim\u2019s scope.",
  "The student calibrates claims to evidence, uses qualifications purposefully, and distinguishes reasonable precision from unnecessary hedging.",
 ],
 "Comparison": [
  "An examination of meaningful similarities between two or more subjects.",
  "Establish the basis of comparison; select relevant dimensions; describe each subject using the same dimensions; explain the significance of the similarities.",
  "Are the subjects genuinely comparable? Are equivalent dimensions used? Does the student merely list similarities without explaining their importance?",
  "Ask what common question can be asked about both subjects and why the resulting similarity matters.",
  "The student selects illuminating comparison dimensions and uses similarities to support interpretation or argument.",
 ],
 "Contrast": [
  "An examination of meaningful differences between two or more subjects.",
  "Establish the basis of contrast; compare the subjects along equivalent dimensions; identify significant differences; explain what follows from those differences.",
  "Are differences listed randomly? Are unlike features being compared? Is the significance of the contrast unclear?",
  "Ask the student to compare both subjects on one shared dimension and explain why the difference matters.",
  "The student constructs balanced contrasts and draws warranted conclusions from significant differences.",
 ],
 "Cause-and-Effect Explanation": [
  "An account of how and why one condition, event, or process contributes to another.",
  "Identify the proposed cause and outcome; explain the mechanism connecting them; consider contributing conditions, alternative causes, sequence, and evidence; avoid confusing correlation with causation.",
  "Is causation asserted without a mechanism? Are multiple causes reduced to one? Could the relationship be reversed, coincidental, or mediated by another factor?",
  "Ask, \u201cBy what process would this produce that result?\u201d Help the student identify intermediate steps and competing explanations.",
  "The student explains causal mechanisms, considers interacting causes, and qualifies causal conclusions according to the evidence.",
 ],
 "Classification": [
  "The organization of examples into meaningful groups based on shared criteria.",
  "Identify the purpose of grouping; establish a consistent criterion; define each category; assign examples according to the criterion; address overlap or borderline cases.",
  "Are categories based on one clear principle? Do they overlap unnecessarily? Are important cases omitted or forced into unsuitable groups?",
  "Ask what feature is being used to sort the examples and whether that feature is applied consistently to every case.",
  "The student creates purposeful, coherent categories and revises them when examples reveal ambiguity or overlap.",
 ],
 "Transition": [
  "Language or structure that helps readers understand how one idea, sentence, paragraph, or section relates to another.",
  "Determine the actual relationship between ideas; express that relationship through wording, repetition, sentence structure, or sequencing; provide enough guidance without mechanical labeling.",
  "Can the reader follow the shift? Is the relationship additive, contrasting, causal, sequential, illustrative, or concessive? Is the transition word inaccurate or superficial?",
  "Ask the student to state the relationship between the two ideas in ordinary language, then express that relationship in the writing.",
  "The student creates transitions based on genuine conceptual relationships and uses them flexibly without relying on a stock list.",
 ],
}

DEEP = {}
def add(el, reader, writer, fr, cd, pm, early, partial, rdd, di, rs, tr, neighbor):
    DEEP[el] = dict(reader_function=reader, writer_function=writer, functional_relationships=fr,
        common_difficulties=cd, productive_misconceptions=pm,
        indicators_of_development={"early": early, "partial": partial},
        recognition_diagnostics_detailed=rdd, developmental_invitations=di,
        revision_strategies=rs, transfer=tr, _neighbor=neighbor)

# ---- Definition ----
add("Definition",
 "Gives the reader a shared, sufficient understanding of a term before it does work in the argument.",
 "Forces the writer to make a concept's meaning explicit and complete enough for this reader and purpose.",
 {"purpose":"A definition serves the argument by making a load-bearing term mean the same thing for writer and reader.",
  "reader":"Supplies the meaning the reader needs; tested by whether the intended reader would understand it.",
  "neighboring_components":"Grounds the Concept it names; supports Central Claim/Thesis when a key term is contested.",
  "overall_organization":"Placed where the term first does work; elaborated only as far as the reader needs."},
 [{"type":"circular","description":"Defines the term using the term itself."},
  {"type":"vague","description":"Too general to fix the meaning for this reader."},
  {"type":"over_or_under_broad","description":"Includes too much or too little to match the intended meaning."},
  {"type":"example_for_definition","description":"Offers an instance in place of the general meaning."}],
 [{"misconception":"A dictionary definition settles the meaning.","why_productive":"The learner values precision and authority.","leverage":"Move to context: the definition must fit how the term is used in THIS argument."},
  {"misconception":"Only hard words need defining.","why_productive":"The learner senses definitions clarify.","leverage":"Shift to load-bearing terms: define what the argument depends on, familiar or not."}],
 "Uses a term without explaining it, or defines it circularly/by example.",
 "Explains the term but too vaguely or broadly for the reader; sharpens when one unclear word is probed.",
 {"attempting":"Is the learner stating a general meaning, an example, or restating the term? Quote it.",
  "control_level":"Would the intended reader understand it? Non-circular, appropriately scoped? Map to early/partial/independent/flexible.",
  "likely_misconception":"Term-in-its-own-definition -> circular; instance offered -> example_for_definition.",
  "next_move":"Ask the learner to explain the concept in ordinary language, then probe one unclear word for elaboration."},
 [{"type":"clarify","purpose":"State the term's basic meaning in plain language.","use_when":"The definition is vague or circular.","avoid_when":"Meaning is already clear to the reader."},
  {"type":"contrast","purpose":"Distinguish the term from a related concept.","use_when":"The boundary is fuzzy.","avoid_when":"The distinction is already sharp."},
  {"type":"predict_reader_understanding","purpose":"Test whether the intended reader would grasp it.","use_when":"Audience fit is uncertain.","avoid_when":"Reader fit is confirmed."},
  {"type":"reflect","purpose":"Have the learner say when a term needs defining.","use_when":"Consolidating.","avoid_when":"The concept is not yet clear."}],
 ["Replace a circular definition with the term's defining qualities in plain words.",
  "Add a distinction from the nearest related concept where the boundary matters.",
  "Trim or extend the scope so it matches the intended meaning exactly."],
 {"other_genres":"Making load-bearing terms explicit transfers to technical, legal, and scientific writing.",
  "other_assignments":"'Would the reader understand this term as I mean it?' applies to any argument.",
  "other_disciplines":"Disciplines fix meanings differently; the sufficiency-for-the-reader test is constant.",
  "future_writing":"Foundational for specifications, policy, and technical documentation."},
 "Concept")

# ---- Concept ----
add("Concept",
 "Gives the reader a general idea that organizes and interprets the particular cases the writing discusses.",
 "Requires the writer to hold an abstraction steadily — its defining features and its boundaries.",
 {"purpose":"Concepts let the argument generalize; the purpose determines which concept is doing the organizing.",
  "reader":"Lets the reader see what unites the particulars and what would not count.",
  "neighboring_components":"Named by a Definition; instantiated by Examples; organizes Classification.",
  "overall_organization":"Governs how particulars are grouped and interpreted across the piece."},
 [{"type":"term_without_understanding","description":"Uses a concept word without grasping the idea behind it."},
  {"type":"example_as_concept","description":"Treats a single instance as the general idea."},
  {"type":"inconsistent_features","description":"The qualities that define the concept shift from case to case."},
  {"type":"unbounded","description":"No sense of what would NOT count as an instance."}],
 [{"misconception":"A concept is just its examples.","why_productive":"The learner reasons from concrete cases.","leverage":"Lift to the general: what do the examples share that makes them instances?"},
  {"misconception":"If I can name it, I understand it.","why_productive":"The learner has the vocabulary.","leverage":"Test understanding by boundaries: what would not count?"}],
 "Uses the term concretely or interchangeably with an example; cannot state the general idea.",
 "States the general idea but its defining features waver or its boundaries are unclear; steadies when tested with non-instances.",
 {"attempting":"Is the learner naming, exemplifying, or abstracting the concept? Quote the usage.",
  "control_level":"Can the learner state defining features, valid/invalid instances, and use it consistently? Map to levels.",
  "likely_misconception":"Instance stands in -> example_as_concept; shifting features -> inconsistent_features.",
  "next_move":"Ask what different examples share and what would NOT count, then help state the general idea."},
 [{"type":"clarify","purpose":"State the general idea behind the examples.","use_when":"Only instances are present.","avoid_when":"The abstraction is already stated."},
  {"type":"contrast","purpose":"Separate instances from non-instances.","use_when":"Boundaries are unclear.","avoid_when":"The boundary is firm."},
  {"type":"connect","purpose":"Tie examples to the general idea.","use_when":"Cases float free of the concept.","avoid_when":"The link is explicit."},
  {"type":"reflect","purpose":"Have the learner define the concept in their own words.","use_when":"Consolidating.","avoid_when":"Understanding is not yet stable."}],
 ["State what the examples share as the concept's defining features.",
  "Name one thing that would NOT count and use it to sharpen the boundary.",
  "Make the defining features consistent across every case used."],
 {"other_genres":"Holding an abstraction transfers to analysis, theory, and interpretation.",
  "other_assignments":"'What general idea organizes these particulars?' applies broadly.",
  "other_disciplines":"Concepts vary by field; abstraction and boundary-setting are constant.",
  "future_writing":"Foundational for conceptual, analytical, and research writing."},
 "Definition")

# ---- Central Claim ----
add("Central Claim",
 "Tells the reader the main thing they are being asked to understand, consider, or accept.",
 "Commits the writer to a genuine, scoped, supportable position rather than a topic or truism.",
 {"purpose":"Operationalizes the purpose as an assertion; the purpose sets what the reader should do with the claim.",
  "reader":"Gives the reader something to weigh and a standard of proof.",
  "neighboring_components":"Close kin of the Thesis; developed by Supporting Claims; bounded by Qualification.",
  "overall_organization":"What the body must earn; parts that do not bear on it signal drift or a mis-scoped claim."},
 [{"type":"not_an_assertion","description":"Presents a topic or observation rather than a position."},
  {"type":"obvious","description":"States something no reasonable reader would dispute."},
  {"type":"too_absolute","description":"Overclaims beyond what the evidence can support."},
  {"type":"disconnected","description":"Not clearly tied to the task or the argument that follows."}],
 [{"misconception":"A strong claim is one stated most forcefully.","why_productive":"The learner values conviction.","leverage":"Redirect force toward supportability and scope, not volume."},
  {"misconception":"A claim must be absolute to be strong.","why_productive":"The learner wants a clear stance.","leverage":"Introduce qualification: a precise, bounded claim is stronger than a sweeping one."}],
 "Offers a topic or an obvious statement; cannot say why anyone would question it.",
 "States a genuine assertion but its scope is off or its support is unanticipated; refines when asked who might disagree.",
 {"attempting":"Is the learner naming a topic or asserting a position? Quote the candidate claim.",
  "control_level":"Genuine, clear, supportable, appropriately scoped, tied to the task? Map to levels.",
  "likely_misconception":"No dispute possible -> obvious; sweeping -> too_absolute.",
  "next_move":"Ask what the writer wants the reader to believe and why someone might question it, then refine."},
 [{"type":"clarify","purpose":"Turn a topic into an assertion.","use_when":"There is no genuine claim.","avoid_when":"A clear claim exists."},
  {"type":"justify","purpose":"Surface why someone might disagree.","use_when":"The claim is obvious.","avoid_when":"Contestability is clear."},
  {"type":"test","purpose":"Check the claim against available support.","use_when":"The claim may overreach.","avoid_when":"Support is mapped."},
  {"type":"connect","purpose":"Tie the claim to the task.","use_when":"It is disconnected.","avoid_when":"It is well anchored."}],
 ["Rewrite a topic as a position a thoughtful reader could dispute.",
  "Right-size the claim to what the evidence can support (add a qualification if needed).",
  "Reconnect the claim to the assignment's actual question."],
 {"other_genres":"The 'assertion the reader must weigh' function persists across argument and analysis.",
  "other_assignments":"'What am I asking the reader to accept, and why doubt it?' applies broadly.",
  "other_disciplines":"Standards of support differ; the contestable, scoped claim is constant.",
  "future_writing":"Foundational for proposals, recommendations, and position papers."},
 "Thesis")

# ---- Supporting Claim ----
add("Supporting Claim",
 "Shows the reader one part of the case for the central claim, advancing the argument step by step.",
 "Makes the writer turn each section into a distinct assertion that contributes to the thesis, not just information.",
 {"purpose":"Each supporting claim carries one share of the purpose toward the central claim.",
  "reader":"Lets the reader see how the argument is built, one contribution at a time.",
  "neighboring_components":"Serves the Thesis/Central Claim; realized as a paragraph's Topic Sentence; earned by Evidence and Explanation.",
  "overall_organization":"Supporting claims should be distinct, logically ordered, and each traceable to the thesis."},
 [{"type":"information_not_claim","description":"Presents facts about the topic without asserting anything."},
  {"type":"non_contributing","description":"Makes a claim that does not advance the thesis."},
  {"type":"implicit_relationship","description":"Its connection to the thesis is left unstated."},
  {"type":"overlapping","description":"Repeats another supporting claim rather than adding a distinct step."}],
 [{"misconception":"A paragraph's job is to present information on the topic.","why_productive":"The learner is gathering relevant material.","leverage":"Shift from information to contribution: what does this paragraph help show about the thesis?"},
  {"misconception":"If it's on topic, it supports the thesis.","why_productive":"The learner sees relevance.","leverage":"Introduce contribution as an explicit assertion tied to the claim."}],
 "Presents topic information without a clear assertion or link to the thesis.",
 "States a contributing claim but leaves its relationship to the thesis implicit or overlaps others; clarifies when asked what it shows.",
 {"attempting":"Is the paragraph asserting a contribution or presenting information? Quote its point.",
  "control_level":"Distinct claim? Contributes to the thesis? Relationship explicit? Adequately supported? Map to levels.",
  "likely_misconception":"Facts only -> information_not_claim; unstated link -> implicit_relationship.",
  "next_move":"Ask what the paragraph helps show about the thesis, then state that contribution as a claim."},
 [{"type":"clarify","purpose":"Turn topic information into a contributing claim.","use_when":"The paragraph only reports.","avoid_when":"A claim is present."},
  {"type":"connect","purpose":"Make the claim's link to the thesis explicit.","use_when":"The relationship is implicit.","avoid_when":"It is stated."},
  {"type":"reorganize","purpose":"Order supporting claims into a logical build.","use_when":"Claims are unordered or overlap.","avoid_when":"The sequence is sound."},
  {"type":"reflect","purpose":"Have the learner state each claim's contribution.","use_when":"Consolidating.","avoid_when":"Contributions are unclear."}],
 ["Rewrite topic information as an assertion that advances the thesis.",
  "Add a clause making the claim's contribution to the thesis explicit.",
  "Merge or cut a supporting claim that overlaps another; order the rest as a build."],
 {"other_genres":"Building a case in distinct steps transfers to reports and analyses.",
  "other_assignments":"'What does this section contribute to the whole claim?' applies broadly.",
  "other_disciplines":"Support standards differ; step-by-step contribution is constant.",
  "future_writing":"Foundational for structured argument and recommendation writing."},
 "Thesis")

# ---- Example ----
add("Example",
 "Gives the reader a concrete case that makes an abstract idea understandable or credible.",
 "Requires the writer to choose a representative case AND say which of its features illustrate the idea.",
 {"purpose":"Examples serve the idea they illustrate; the purpose sets what the case must demonstrate.",
  "reader":"Turns an abstraction into something the reader can picture and test.",
  "neighboring_components":"A form of Evidence/Supporting Detail; instantiates a Concept; develops a Paragraph.",
  "overall_organization":"Placed where an idea becomes too abstract; explained, not left to speak for itself."},
 [{"type":"unexplained","description":"A case is given but not tied to the idea it should illustrate."},
  {"type":"unrepresentative","description":"The case does not fairly stand for the general idea."},
  {"type":"idea_too_abstract","description":"The idea needed an example and none is offered."},
  {"type":"single_insufficient","description":"One case is treated as proof of a general claim."}],
 [{"misconception":"An example speaks for itself.","why_productive":"The learner values concreteness.","leverage":"Add the interpretive step: name which features illustrate the idea."},
  {"misconception":"More examples make a stronger point.","why_productive":"The learner is developing the idea.","leverage":"Shift to representativeness and explanation over quantity."}],
 "Drops a case in without explaining what it demonstrates.",
 "Chooses a relevant case but under-explains or over-generalizes from it; sharpens when asked which features illustrate the idea.",
 {"attempting":"Is the learner illustrating with a case and explaining it, or just inserting it? Quote the example.",
  "control_level":"Relevant, representative, explained, and appropriately generalized? Map to levels.",
  "likely_misconception":"Case with no interpretation -> unexplained; one case as proof -> single_insufficient.",
  "next_move":"Ask the learner to name exactly which features of the case illustrate the larger idea."},
 [{"type":"clarify","purpose":"Name what the example demonstrates.","use_when":"The case is unexplained.","avoid_when":"Its point is clear."},
  {"type":"evaluate","purpose":"Judge whether the case is representative.","use_when":"The example may be atypical.","avoid_when":"It clearly stands for the idea."},
  {"type":"connect","purpose":"Tie the case's features to the idea.","use_when":"The link is loose.","avoid_when":"Features are already tied."},
  {"type":"reflect","purpose":"Have the learner explain the example's relevance.","use_when":"Consolidating.","avoid_when":"Relevance is unclear."}],
 ["Add a sentence naming which features of the case illustrate the idea.",
  "Replace an atypical case with one that fairly represents the idea.",
  "Qualify or add cases where one example is treated as general proof."],
 {"other_genres":"Illustration-with-interpretation transfers to explanation, teaching, and narrative.",
  "other_assignments":"'Which features of this case show my point?' applies broadly.",
  "other_disciplines":"What counts as representative varies; the explain-the-case habit is constant.",
  "future_writing":"Foundational for explanatory and instructional writing."},
 "Evidence")

# ---- Counterargument ----
add("Counterargument",
 "Shows the reader the strongest reasonable view against the writer's position, taken seriously.",
 "Requires the writer to find and fairly state a genuine objection rather than a straw man.",
 {"purpose":"Serves persuasion/analysis by testing the claim against real opposition.",
  "reader":"Assures the reader their likely doubts have been considered.",
  "neighboring_components":"Answered by the Rebuttal/Response; often prompts a Qualification of the Central Claim.",
  "overall_organization":"Placed where the reader's doubt is strongest; represented before it is answered."},
 [{"type":"ignored","description":"A meaningful opposing view is left unaddressed."},
  {"type":"straw_man","description":"The objection is weakened or caricatured so it is easy to defeat."},
  {"type":"unexplained","description":"An objection is named but its reasoning is not shown."},
  {"type":"significance_unclear","description":"Why the objection matters to the argument is not established."}],
 [{"misconception":"Raising objections weakens my argument.","why_productive":"The learner wants a strong case.","leverage":"Reframe: engaging the strongest objection makes the case more credible."},
  {"misconception":"Any opposing point counts as a counterargument.","why_productive":"The learner is considering other views.","leverage":"Raise the bar to the strongest reasonable version."}],
 "Omits opposing views or states an easily defeated version.",
 "Names a real objection but represents it thinly or without its significance; strengthens when asked for the strongest version.",
 {"attempting":"Is the learner engaging a real objection, a straw man, or none? Quote it.",
  "control_level":"Genuine, charitable, reasoned, and shown to matter? Map to levels.",
  "likely_misconception":"Weak version -> straw_man; no reasoning -> unexplained.",
  "next_move":"Ask what a thoughtful person might see differently, then help state the strongest reasonable version."},
 [{"type":"clarify","purpose":"Identify a genuine point of disagreement.","use_when":"No real objection is present.","avoid_when":"A strong one is stated."},
  {"type":"justify","purpose":"Show the reasoning behind the objection.","use_when":"The objection is thin.","avoid_when":"Its logic is clear."},
  {"type":"evaluate","purpose":"Test whether the strongest version is represented.","use_when":"A straw man is suspected.","avoid_when":"It is charitable."},
  {"type":"connect","purpose":"Show why the objection matters here.","use_when":"Significance is unclear.","avoid_when":"It is established."}],
 ["Replace a weak objection with the strongest reasonable version.",
  "Add the reasoning that makes the objection genuinely challenging.",
  "State why this objection matters to the specific claim."],
 {"other_genres":"Charitable engagement with opposition transfers to argument, analysis, and negotiation.",
  "other_assignments":"'What is the strongest case against me?' applies to any argument.",
  "other_disciplines":"Forms of objection differ; charity and genuineness are constant.",
  "future_writing":"Foundational for persuasive, legal, and policy writing."},
 "Rebuttal / Response")

# ---- Rebuttal / Response ----
add("Rebuttal / Response",
 "Shows the reader how the writer answers a real objection — engaging it, not dismissing it.",
 "Requires the writer to grant what is valid, then show limits, and revise or defend accordingly.",
 {"purpose":"Completes the argumentative exchange the Counterargument opened.",
  "reader":"Lets the reader see the claim survive (or adapt to) genuine challenge.",
  "neighboring_components":"Responds to the Counterargument; frequently produces a Qualification of the Central Claim.",
  "overall_organization":"Follows the objection; may reshape the claim rather than merely defend it."},
 [{"type":"dismissive","description":"Waves the objection away instead of engaging its reasoning."},
  {"type":"misses_objection","description":"Answers a different point than the one raised."},
  {"type":"defends_when_should_qualify","description":"Insists on the original claim where a qualification is warranted."},
  {"type":"concedes_too_much","description":"Grants so much that the original claim collapses unnecessarily."}],
 [{"misconception":"A rebuttal must fully defeat the objection.","why_productive":"The learner wants a decisive case.","leverage":"Introduce qualification: sometimes the right move is to refine the claim."},
  {"misconception":"Acknowledging validity is losing.","why_productive":"The learner defends their position.","leverage":"Reframe: granting what's valid then bounding it is stronger engagement."}],
 "Dismisses or ignores the objection, or answers a different point.",
 "Engages the objection but either over-defends or over-concedes; calibrates when asked what the objection gets right and where it stops applying.",
 {"attempting":"Is the learner engaging, dismissing, or missing the objection? Quote the response.",
  "control_level":"Addresses the actual objection, grants the valid, bounds the rest, revises/defends appropriately? Map to levels.",
  "likely_misconception":"Wave-away -> dismissive; over-insistence -> defends_when_should_qualify.",
  "next_move":"Ask what the counterargument gets right and where its reasoning no longer applies, then refine the position."},
 [{"type":"clarify","purpose":"Name what is valid in the objection.","use_when":"The response is dismissive.","avoid_when":"Validity is already acknowledged."},
  {"type":"evaluate","purpose":"Decide whether to qualify or defend.","use_when":"The claim may need bounding.","avoid_when":"The right move is clear."},
  {"type":"justify","purpose":"Show where the objection's reasoning stops applying.","use_when":"Limits are unstated.","avoid_when":"They are shown."},
  {"type":"connect","purpose":"Tie the response back to the original claim.","use_when":"The exchange floats free.","avoid_when":"It is linked."}],
 ["Acknowledge what the objection gets right before answering it.",
  "Qualify the original claim where the objection has genuine force.",
  "Refocus a response that answers a different point than the one raised."],
 {"other_genres":"Engaging then bounding a challenge transfers to argument, debate, and review responses.",
  "other_assignments":"'What is valid here, and where does it stop?' applies to any objection.",
  "other_disciplines":"Norms of concession differ; genuine engagement is constant.",
  "future_writing":"Foundational for rebuttals, reviewer responses, and negotiation."},
 "Counterargument")

# ---- Qualification ----
add("Qualification",
 "Tells the reader exactly how far the claim reaches — its conditions, degree, and limits.",
 "Requires the writer to match the claim's language to what the evidence actually supports.",
 {"purpose":"Keeps the claim honest to the evidence, serving credibility and precision.",
  "reader":"Prevents the reader from taking the claim further than warranted.",
  "neighboring_components":"Bounds the Central Claim/Thesis; often results from a Rebuttal/Response; interacts with Evidence.",
  "overall_organization":"Applied wherever a claim would otherwise overreach; not scattered as reflexive hedging."},
 [{"type":"too_absolute","description":"States the claim more certainly or broadly than the evidence permits."},
  {"type":"over_hedged","description":"So many qualifiers that the claim says almost nothing."},
  {"type":"unspecified_conditions","description":"Limits are vaguely gestured at rather than specified (who/when/to what degree)."},
  {"type":"misplaced","description":"Qualifies a claim that does not need it while leaving an overreaching one absolute."}],
 [{"misconception":"Qualifying makes writing sound weak.","why_productive":"The learner wants confident prose.","leverage":"Reframe: precise limits make a claim more, not less, defensible."},
  {"misconception":"Hedge everything to be safe.","why_productive":"The learner is cautious about overreach.","leverage":"Introduce calibration: qualify to fit the evidence, not reflexively."}],
 "States claims absolutely, or hedges everything, without matching language to evidence.",
 "Qualifies in places but conditions are vague or misplaced; calibrates when asked 'for whom, when, to what degree.'",
 {"attempting":"Is the learner calibrating the claim to evidence or over/under-hedging? Quote the claim.",
  "control_level":"Are conditions/degree/scope specified and evidence-matched, without emptiness? Map to levels.",
  "likely_misconception":"Sweeping -> too_absolute; everything hedged -> over_hedged.",
  "next_move":"Ask 'Is this always true? For whom, under what conditions, to what degree?' then revise scope."},
 [{"type":"test","purpose":"Check the claim against what the evidence supports.","use_when":"The claim may overreach.","avoid_when":"It already fits the evidence."},
  {"type":"clarify","purpose":"Specify the conditions/degree of the claim.","use_when":"Limits are vague.","avoid_when":"They are precise."},
  {"type":"evaluate","purpose":"Decide whether a qualifier is needed at all.","use_when":"Hedging seems reflexive.","avoid_when":"The qualifier is load-bearing."},
  {"type":"reflect","purpose":"Have the learner distinguish precision from hedging.","use_when":"Consolidating.","avoid_when":"The distinction is unclear."}],
 ["Add specific conditions (who/when/to what degree) to an overreaching claim.",
  "Cut reflexive hedges that drain a claim of meaning.",
  "Move a qualification onto the claim that actually needs bounding."],
 {"other_genres":"Calibrating certainty to evidence transfers to scientific, legal, and analytical writing.",
  "other_assignments":"'How far does this claim actually reach?' applies to any assertion.",
  "other_disciplines":"Conventions for hedging differ; evidence-calibration is constant.",
  "future_writing":"Foundational for research, risk, and policy writing."},
 "Central Claim")

# ---- Comparison ----
add("Comparison",
 "Shows the reader meaningful similarities between subjects and why those similarities matter.",
 "Requires the writer to set a basis, use equivalent dimensions, and interpret the likeness.",
 {"purpose":"Comparison serves interpretation or argument, not a list of likenesses for its own sake.",
  "reader":"Lets the reader see what two subjects share along the same terms.",
  "neighboring_components":"Paired with Contrast; a mode of Organization; supports a Central Claim.",
  "overall_organization":"Structured by shared dimensions; significance stated, not left implicit."},
 [{"type":"incomparable","description":"The subjects are not genuinely comparable on the chosen basis."},
  {"type":"mismatched_dimensions","description":"Different features of each subject are compared rather than equivalent ones."},
  {"type":"list_without_significance","description":"Similarities are listed but their importance is not explained."},
  {"type":"no_basis","description":"No common question or basis for the comparison is established."}],
 [{"misconception":"Comparing means listing things that are alike.","why_productive":"The learner sees connections.","leverage":"Add significance: why does the similarity matter to the point?"},
  {"misconception":"Any two subjects can be compared.","why_productive":"The learner is drawing links.","leverage":"Require a genuine basis and equivalent dimensions."}],
 "Lists similarities with no shared basis or significance.",
 "Compares on some equivalent dimensions but leaves significance implicit; deepens when asked why the similarity matters.",
 {"attempting":"Is the learner using a basis and equivalent dimensions, or listing likenesses? Quote the comparison.",
  "control_level":"Comparable subjects, equivalent dimensions, significance explained? Map to levels.",
  "likely_misconception":"Uneven features -> mismatched_dimensions; bare list -> list_without_significance.",
  "next_move":"Ask what common question can be put to both subjects and why the resulting similarity matters."},
 [{"type":"clarify","purpose":"Establish the basis of comparison.","use_when":"No common question is set.","avoid_when":"A basis exists."},
  {"type":"reorganize","purpose":"Align the comparison on equivalent dimensions.","use_when":"Features are mismatched.","avoid_when":"Dimensions match."},
  {"type":"justify","purpose":"Explain why the similarity matters.","use_when":"Significance is missing.","avoid_when":"It is stated."},
  {"type":"reflect","purpose":"Have the learner state what the comparison shows.","use_when":"Consolidating.","avoid_when":"The point is unclear."}],
 ["State a common question both subjects answer, then compare on those terms.",
  "Align the comparison so equivalent dimensions are used for each subject.",
  "Add the significance: what the similarity shows for the argument."],
 {"other_genres":"Basis + dimensions + significance transfers to analysis, review, and evaluation.",
  "other_assignments":"'On what basis, and why does the likeness matter?' applies broadly.",
  "other_disciplines":"Comparanda differ; the equivalent-dimensions discipline is constant.",
  "future_writing":"Foundational for evaluative and analytical writing."},
 "Contrast")

# ---- Contrast ----
add("Contrast",
 "Shows the reader meaningful differences between subjects and what follows from them.",
 "Requires the writer to compare equivalent dimensions and draw a warranted conclusion.",
 {"purpose":"Contrast serves interpretation or argument by making significant differences do work.",
  "reader":"Lets the reader see how subjects differ along the same terms and why it matters.",
  "neighboring_components":"Paired with Comparison; a mode of Organization; supports a Central Claim.",
  "overall_organization":"Structured by shared dimensions; conclusion drawn from significant differences."},
 [{"type":"random_differences","description":"Differences are listed without a shared basis."},
  {"type":"unlike_features","description":"Non-equivalent features of the subjects are contrasted."},
  {"type":"significance_unclear","description":"What follows from the differences is not explained."},
  {"type":"trivial","description":"The differences noted do not matter to the point."}],
 [{"misconception":"Contrast means listing differences.","why_productive":"The learner notices distinctions.","leverage":"Add consequence: what follows from the difference?"},
  {"misconception":"Any difference is worth noting.","why_productive":"The learner is discriminating.","leverage":"Focus on differences significant to the argument."}],
 "Lists differences with no shared basis or consequence.",
 "Contrasts on some equivalent dimensions but leaves the consequence implicit; deepens when asked why the difference matters.",
 {"attempting":"Is the learner contrasting on equivalent dimensions with a conclusion, or listing? Quote it.",
  "control_level":"Shared basis, equivalent dimensions, significant differences, warranted conclusion? Map to levels.",
  "likely_misconception":"Uneven features -> unlike_features; no consequence -> significance_unclear.",
  "next_move":"Ask the learner to contrast both subjects on one shared dimension and explain why the difference matters."},
 [{"type":"clarify","purpose":"Establish the shared basis of contrast.","use_when":"Differences are random.","avoid_when":"A basis exists."},
  {"type":"reorganize","purpose":"Contrast on equivalent dimensions.","use_when":"Unlike features are compared.","avoid_when":"Dimensions match."},
  {"type":"justify","purpose":"Draw what follows from the differences.","use_when":"Consequence is missing.","avoid_when":"It is stated."},
  {"type":"reflect","purpose":"Have the learner state the contrast's point.","use_when":"Consolidating.","avoid_when":"The point is unclear."}],
 ["Choose one shared dimension and contrast both subjects on it.",
  "Add the conclusion the significant difference warrants.",
  "Drop trivial differences that do not serve the argument."],
 {"other_genres":"Significant-difference reasoning transfers to analysis, evaluation, and decision writing.",
  "other_assignments":"'What difference matters, and what follows?' applies broadly.",
  "other_disciplines":"Comparanda differ; drawing warranted conclusions is constant.",
  "future_writing":"Foundational for comparative analysis and recommendations."},
 "Comparison")

# ---- Cause-and-Effect Explanation ----
add("Cause-and-Effect Explanation",
 "Shows the reader how and why one thing produces another, not merely that they co-occur.",
 "Requires the writer to supply a mechanism and weigh alternative or interacting causes.",
 {"purpose":"Serves explanation/argument by making a causal relationship intelligible and warranted.",
  "reader":"Lets the reader follow the process from cause to outcome.",
  "neighboring_components":"A form of Explanation/Analysis; supported by Evidence; may bound conclusions with Qualification.",
  "overall_organization":"Sequenced by the causal process; alternatives acknowledged before conclusions."},
 [{"type":"no_mechanism","description":"Causation is asserted without explaining the connecting process."},
  {"type":"single_cause","description":"Multiple contributing causes are reduced to one."},
  {"type":"correlation_as_cause","description":"Co-occurrence is treated as causation."},
  {"type":"reversible_or_mediated","description":"The relationship could be reversed, coincidental, or run through another factor."}],
 [{"misconception":"If B follows A, A caused B.","why_productive":"The learner notices sequence.","leverage":"Introduce mechanism: by what process would A produce B?"},
  {"misconception":"Each effect has one cause.","why_productive":"The learner seeks clear explanations.","leverage":"Open to interacting and alternative causes."}],
 "Asserts causation from sequence or correlation, with no mechanism.",
 "Proposes a mechanism but overlooks alternative/interacting causes or overstates certainty; qualifies when competing explanations are raised.",
 {"attempting":"Is the learner explaining a mechanism or asserting a link? Quote the causal claim.",
  "control_level":"Mechanism explained, alternatives considered, causation vs correlation handled, conclusions qualified? Map to levels.",
  "likely_misconception":"Co-occurrence -> correlation_as_cause; one cause -> single_cause.",
  "next_move":"Ask 'By what process would this produce that result?' and surface intermediate steps and competing causes."},
 [{"type":"clarify","purpose":"Name the mechanism connecting cause and effect.","use_when":"Only a link is asserted.","avoid_when":"A mechanism is given."},
  {"type":"evaluate","purpose":"Weigh alternative or interacting causes.","use_when":"One cause is assumed.","avoid_when":"Alternatives are handled."},
  {"type":"test","purpose":"Check whether correlation is being read as cause.","use_when":"Evidence is co-occurrence.","avoid_when":"Causation is warranted."},
  {"type":"justify","purpose":"Qualify the causal conclusion to the evidence.","use_when":"Certainty is overstated.","avoid_when":"It is calibrated."}],
 ["Add the intermediate steps that show how the cause produces the effect.",
  "Acknowledge alternative or contributing causes before concluding.",
  "Qualify a causal claim that rests only on correlation."],
 {"other_genres":"Mechanism-based reasoning transfers to scientific, historical, and analytical writing.",
  "other_assignments":"'By what process, and what else could explain it?' applies broadly.",
  "other_disciplines":"Causal standards differ; mechanism and alternatives are constant.",
  "future_writing":"Foundational for analysis, diagnostics, and research writing."},
 "Explanation / Analysis")

# ---- Classification ----
add("Classification",
 "Shows the reader a set of cases organized into meaningful groups by a consistent principle.",
 "Requires the writer to choose one grouping criterion and apply it consistently.",
 {"purpose":"Classification serves understanding when the grouping principle fits the purpose.",
  "reader":"Lets the reader see how many cases are organized and why.",
  "neighboring_components":"Organizes Concepts and Examples; a mode of Organization.",
  "overall_organization":"Structured by one criterion; overlap and borderline cases addressed."},
 [{"type":"inconsistent_criterion","description":"Categories rest on more than one sorting principle at once."},
  {"type":"overlapping","description":"Categories overlap so cases fit several groups."},
  {"type":"omitted_cases","description":"Important cases are left ungrouped or forced into unsuitable groups."},
  {"type":"purposeless","description":"The grouping does not serve the writing's purpose."}],
 [{"misconception":"Any grouping is a classification.","why_productive":"The learner is organizing material.","leverage":"Introduce a single consistent criterion applied to every case."},
  {"misconception":"Categories should be exhaustive at all costs.","why_productive":"The learner wants completeness.","leverage":"Tie categories to purpose; address borderline cases honestly."}],
 "Groups cases by shifting or unstated criteria; categories overlap.",
 "Uses a criterion but applies it inconsistently or ignores borderline cases; revises when the sorting feature is tested on every case.",
 {"attempting":"Is the learner sorting by one consistent criterion? Name the criterion and quote the categories.",
  "control_level":"One clear principle, non-overlapping, purposeful, borderline cases handled? Map to levels.",
  "likely_misconception":"Mixed principles -> inconsistent_criterion; fuzzy groups -> overlapping.",
  "next_move":"Ask what feature sorts the examples and whether it is applied consistently to every case."},
 [{"type":"clarify","purpose":"Name the single sorting criterion.","use_when":"The principle is unstated or mixed.","avoid_when":"It is clear and consistent."},
  {"type":"evaluate","purpose":"Test the criterion against every case.","use_when":"Overlap or omissions appear.","avoid_when":"Categories are clean."},
  {"type":"reorganize","purpose":"Reframe categories to fit the purpose.","use_when":"Grouping is purposeless.","avoid_when":"It serves the purpose."},
  {"type":"reflect","purpose":"Have the learner justify the category scheme.","use_when":"Consolidating.","avoid_when":"The scheme is unclear."}],
 ["State one sorting criterion and apply it to every case.",
  "Resolve overlapping categories so each case has a clear home.",
  "Address borderline cases explicitly rather than forcing them."],
 {"other_genres":"Consistent grouping transfers to technical, scientific, and organizational writing.",
  "other_assignments":"'What single feature sorts these, applied to all?' applies broadly.",
  "other_disciplines":"Taxonomies differ; one-criterion consistency is constant.",
  "future_writing":"Foundational for taxonomies, documentation, and analytical structure."},
 "Organization")

# ---- Transition ----
add("Transition",
 "Helps the reader see how one idea, sentence, paragraph, or section relates to another.",
 "Requires the writer to name the real relationship first, then express it — not paste a connective.",
 {"purpose":"Transitions serve coherence by making relationships between ideas visible.",
  "reader":"Signals the relationship (add/contrast/cause/sequence/illustrate/concede) so the reader can follow the shift.",
  "neighboring_components":"Realizes Coherence; connects Paragraphs and Sentences; supports Organization.",
  "overall_organization":"Placed at each shift the reader must track; flexible, not a stock list."},
 [{"type":"inaccurate","description":"The connective names a relationship the ideas do not actually have."},
  {"type":"superficial","description":"A transition word is added without a real conceptual link."},
  {"type":"missing","description":"A shift occurs with no signal, so the reader cannot follow it."},
  {"type":"mechanical","description":"Stock connectives are applied by formula rather than to the relationship."}],
 [{"misconception":"Transitions mean words like 'however' and 'therefore'.","why_productive":"The learner knows connectives help.","leverage":"Move from vocabulary to relationship: name the link, then express it (with words, repetition, or structure)."},
  {"misconception":"Every sentence needs a transition word.","why_productive":"The learner attends to flow.","leverage":"Focus on genuine shifts the reader must track."}],
 "Adds or omits connectives without identifying the real relationship between ideas.",
 "Signals relationships in places but some are inaccurate or superficial; corrects when the relationship is stated in plain words first.",
 {"attempting":"Is the learner naming the relationship or pasting a connective? Quote the transition.",
  "control_level":"Accurate relationship, expressed flexibly, reader can follow the shift? Map to levels.",
  "likely_misconception":"Word without link -> superficial; wrong connective -> inaccurate.",
  "next_move":"Ask the learner to state the relationship between the two ideas in ordinary language, then express it in the writing."},
 [{"type":"clarify","purpose":"State the actual relationship between two ideas.","use_when":"A shift is unsignaled or mislabeled.","avoid_when":"The relationship is clear and accurate."},
  {"type":"connect","purpose":"Express the relationship (words, repetition, or structure).","use_when":"The link is only implied.","avoid_when":"It is expressed."},
  {"type":"evaluate","purpose":"Check whether a connective names the true relationship.","use_when":"A connective may be inaccurate.","avoid_when":"It fits."},
  {"type":"reflect","purpose":"Have the learner read the shift as a reader.","use_when":"Consolidating.","avoid_when":"Flow is not yet controlled."}],
 ["Say the relationship between two ideas in plain words, then express it in the text.",
  "Replace an inaccurate connective with one that names the true relationship.",
  "Signal an unmarked shift so the reader can follow it."],
 {"other_genres":"Relationship-first transitions transfer to argument, narrative, and instructions.",
  "other_assignments":"'What is the real relationship, and is it visible?' applies broadly.",
  "other_disciplines":"Preferred connectives differ; the relationship-first habit is constant.",
  "future_writing":"Foundational for coherent reports, analyses, and documentation."},
 "Coherence")

def main():
    kb = json.load(open(KB_PATH, encoding="utf-8"))
    objs = kb["instructional_objects"]
    by_el = {o["element"]: o for o in objs}
    report = []
    for el in CANON:
        assert el not in PILOTS
        o = by_el[el]; d = DEEP[el]; canon = CANON[el]; prov = {}
        o["definition"], o["performance_structure"], o["recognition_diagnostics"], o["next_developmental_moves"], o["indicators_of_control"] = canon
        for k in ["definition","performance_structure","recognition_diagnostics","next_developmental_moves","indicators_of_control"]:
            prov[k] = "canonical_verbatim"
        o["reader_function"]=d["reader_function"]; prov["reader_function"]="pattern_interpreted"
        o["writer_function"]=d["writer_function"]; prov["writer_function"]="pattern_interpreted"
        o["functional_relationships"]=d["functional_relationships"]; prov["functional_relationships"]="pattern_interpreted"
        o["common_difficulties"]=d["common_difficulties"]; prov["common_difficulties"]="canonical_derived"
        o["productive_misconceptions"]=d["productive_misconceptions"]; prov["productive_misconceptions"]="pattern_interpreted"
        iodict=dict(d["indicators_of_development"]); iodict["independent"]=canon[4]; iodict["flexible"]=canon[4]
        o["indicators_of_development"]=iodict
        prov["indicators_of_development"]="mixed (independent/flexible=canonical_verbatim; early/partial=pattern_interpreted)"
        o["recognition_diagnostics_detailed"]=d["recognition_diagnostics_detailed"]; prov["recognition_diagnostics_detailed"]="canonical_derived"
        o["developmental_invitations"]=d["developmental_invitations"]; prov["developmental_invitations"]="pattern_interpreted"
        o["followup_decisions"]=followups(el.split(" / ")[0].split("-and-")[0].lower(), d["_neighbor"]); prov["followup_decisions"]="pattern_interpreted"
        o["revision_strategies"]=d["revision_strategies"]; prov["revision_strategies"]="canonical_derived"
        o["stopping_conditions"]=stopping(el.split(" / ")[0].split("-and-")[0].lower()); prov["stopping_conditions"]="pattern_interpreted"
        o["transfer"]=d["transfer"]; prov["transfer"]="pattern_interpreted"
        o["engine_usage"]=copy.deepcopy(ENGINE_USAGE); prov["engine_usage"]="pattern_boilerplate"
        o["canonical_source"]="Writing Elements Chart"; o["enrichment_version"]=ENRICH_VERSION; o["field_provenance"]=prov
        report.append(el)
    with open(KB_PATH,"w",encoding="utf-8") as f:
        json.dump(kb,f,ensure_ascii=False,indent=2)
    print("Enriched", len(report), "objects (batch 2).")

if __name__ == "__main__":
    main()
